language: c++

script:
  - make
  - ls

deploy:
  - provider: releases
    api_key: "${token}"
    file:
      - "testi"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME != "osx"
  - provider: releases
    api_key: "${token}"
    file:
      - "testa"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME == "osx"